name: Update withKDY

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      run: |
        sudo apt-get update
        sudo apt-get install python3.10 python3.10-venv python3.10-dev
        python3.10 -m venv venv
        source venv/bin/activate
    - name: Install dependencies # 1) 스크립트에 필요한 dependency 설치
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run update.py # 2) update.py 실행
      run: |
        python update.py
    - name: Commit changes
      run: |
        git config --global user.name 'withKDY'
        git config --global user.email 'eodyd7072@naver.com'
        git add -A
        git commit -am "auto update readme"
    - name: Push changes
      run: |
        git push
